### ISSUE TITLE
Package dosen't support laravel framework 5.4*

### ISSUE THREAD

**Issue by jason-chang** [hafael/laraflake#1]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for hafael/laraflake ^1.0 -> satisfiable by hafael/laraflake[v1.0.0].
    - Conclusion: remove laravel/framework v5.4.22
    - Conclusion: don't install laravel/framework v5.4.22
    - hafael/laraflake v1.0.0 requires illuminate/support 5.3.* -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/support v5.3.0|don't install laravel/framework v5.4.22
    - don't install illuminate/support v5.3.16|don't install laravel/framework v5.4.22
    - don't install illuminate/support v5.3.23|don't install laravel/framework v5.4.22
    - don't install illuminate/support v5.3.4|don't install laravel/framework v5.4.22
    - Installation request for laravel/framework (locked at v5.4.22, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.22].

Installation failed, reverting ./composer.json to its original content.

**Comment by hafael** [comment]
Sorry, fixed in [v1.1.0](https://packagist.org/packages/hafael/laraflake#v1.1.0).

**Comment by jason-chang** [comment]
Thank you. I fork a brach and config composer "repositories" to use it. But i forgot to make a pull request.

"repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/jason-chang/laraflake"
    }
  ]
